import { daysUntil } from './deadlines';
import type { ActionNeeded, DeadlineStatus, DeadlineType, Purchase, PurchaseDeadline, ProtectionStatus } from '../types/purchase';

export type NormalizedDeadline = PurchaseDeadline & { purchase: Purchase; days: number; status: DeadlineStatus };
export type DeadlineGroup = 'overdue' | 'today' | 'week' | 'month' | 'later';
export const currency = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' });
export const formatMoney = (value: number | null) => value === null ? 'Price not added' : currency.format(value);
export const formatDate = (date: string | null) => date ? new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(`${date}T12:00:00`)) : 'Not added';
export const protectionLabel = (status: ProtectionStatus) => status === 'protected' ? 'Protected' : status === 'attention' ? 'Needs attention' : 'Protection incomplete';
export const deadlineTypeLabel = (type: DeadlineType) => ({ return: 'Return deadline', warranty: 'Warranty expiration', rebate: 'Rebate deadline', custom: 'Custom deadline' })[type];
export function deadlineStatus(date: string | null, now = new Date()): { days: number; status: DeadlineStatus } | null { if (!date) return null; const days = daysUntil(date, now); return { days, status: days < 0 ? 'overdue' : days === 0 ? 'today' : days <= 7 ? 'urgent' : days <= 31 ? 'upcoming' : 'later' }; }
export function normalizedDeadlines(items: Purchase[], now = new Date()): NormalizedDeadline[] { return items.flatMap((purchase) => purchase.deadlines.map((deadline) => { const status = deadlineStatus(deadline.date, now); return { ...deadline, purchase, days: status!.days, status: status!.status }; })).sort((a, b) => a.days - b.days || a.purchase.name.localeCompare(b.purchase.name)); }
export function deadlineGroup(deadline: NormalizedDeadline, now = new Date()): DeadlineGroup { if (deadline.status === 'overdue') return 'overdue'; if (deadline.status === 'today') return 'today'; if (deadline.days <= 7) return 'week'; const target = new Date(`${deadline.date}T12:00:00`); return target.getUTCFullYear() === now.getFullYear() && target.getUTCMonth() === now.getMonth() ? 'month' : 'later'; }
export function groupDeadlines(items: NormalizedDeadline[], now = new Date()): Record<DeadlineGroup, NormalizedDeadline[]> { return items.reduce<Record<DeadlineGroup, NormalizedDeadline[]>>((groups, item) => { groups[deadlineGroup(item, now)].push(item); return groups; }, { overdue: [], today: [], week: [], month: [], later: [] }); }
export function protectedPurchaseCount(items: Purchase[]) { return items.filter((item) => item.protectionStatus !== 'unprotected').length; }
export function protectedValue(items: Purchase[]) { return items.filter((item) => item.protectionStatus !== 'unprotected').reduce((total, item) => total + (item.price ?? 0), 0); }
export function upcomingDeadlines(items: Purchase[], now = new Date()) { return normalizedDeadlines(items, now).filter((deadline) => deadline.days >= 0); }
export function urgentDeadlines(items: Purchase[], now = new Date()) { return normalizedDeadlines(items, now).filter((deadline) => deadline.status === 'today' || deadline.status === 'urgent'); }
export function recentPurchases(items: Purchase[]) { return [...items].sort((a, b) => (b.purchaseDate ?? '').localeCompare(a.purchaseDate ?? '')); }
export function actionNeeded(items: Purchase[], now = new Date()): ActionNeeded[] { const deadlines = normalizedDeadlines(items, now).filter((deadline) => deadline.status === 'overdue' || deadline.status === 'today' || deadline.status === 'urgent').map((deadline) => ({ id: deadline.id, kind: 'deadline' as const, purchase: deadline.purchase, title: deadlineTypeLabel(deadline.type), description: `${deadline.purchase.merchant} · ${formatDate(deadline.date)}`, actionLabel: 'Review', date: deadline.date })); const missing: ActionNeeded[] = []; items.forEach((purchase) => { if (!purchase.hasReceipt) missing.push({ id: `receipt-${purchase.id}`, kind: 'missing_receipt', purchase, title: 'Receipt missing', description: `${purchase.merchant} · Add proof of purchase`, actionLabel: 'Add receipt' }); if (!purchase.hasWarrantyInfo) missing.push({ id: `warranty-${purchase.id}`, kind: 'missing_warranty', purchase, title: 'Warranty information missing', description: `${purchase.merchant} · Add coverage details`, actionLabel: 'Add details' }); }); return [...deadlines, ...missing]; }
