import React, { useMemo, useState } from 'react';
import { Modal, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Feather } from '@expo/vector-icons';
import { colors, radius, spacing, type } from '../design/tokens';
import { deadlineTypeLabel, formatDate, groupDeadlines, type NormalizedDeadline } from '../lib/purchaseSelectors';
import type { DeadlineType, Purchase } from '../types/purchase';
import { Badge, Button, Card, EmptyState, IconButton, Input, SectionHeader } from './ui';

type Filter = 'all' | DeadlineType;
type Sort = 'urgency' | 'date' | 'purchase';
const filters: Array<[Filter, string]> = [['all', 'All'], ['return', 'Returns'], ['warranty', 'Warranties'], ['rebate', 'Rebates'], ['custom', 'Custom']];
const groups: Array<{ id: 'overdue' | 'today' | 'week' | 'month' | 'later'; title: string; detail: string }> = [{ id: 'overdue', title: 'Overdue', detail: 'Needs attention' }, { id: 'today', title: 'Today', detail: 'Due now' }, { id: 'week', title: 'This week', detail: 'Next 7 days' }, { id: 'month', title: 'This month', detail: 'Later this month' }, { id: 'later', title: 'Later', detail: 'Future deadlines' }];
const tone = (status: NormalizedDeadline['status']) => status === 'overdue' || status === 'today' ? 'danger' : status === 'urgent' ? 'warning' : status === 'upcoming' ? 'success' : 'neutral';
const days = (deadline: NormalizedDeadline) => deadline.days < 0 ? `${Math.abs(deadline.days)} days overdue` : deadline.days === 0 ? 'Due today' : deadline.days === 1 ? '1 day remaining' : `${deadline.days} days remaining`;

export function DeadlineRadar({ deadlines, onOpenPurchase, onAdd }: { deadlines: NormalizedDeadline[]; onOpenPurchase: (purchase: Purchase) => void; onAdd: () => void }) {
  const [filter, setFilter] = useState<Filter>('all'); const [sort, setSort] = useState<Sort>('urgency'); const [query, setQuery] = useState(''); const [selected, setSelected] = useState<NormalizedDeadline | null>(null);
  const filtered = useMemo(() => deadlines.filter((deadline) => (filter === 'all' || deadline.type === filter) && `${deadline.purchase.name} ${deadline.purchase.merchant} ${deadlineTypeLabel(deadline.type)}`.toLowerCase().includes(query.toLowerCase())).sort((a, b) => sort === 'purchase' ? a.purchase.name.localeCompare(b.purchase.name) : sort === 'date' ? a.date.localeCompare(b.date) : a.days - b.days || a.purchase.name.localeCompare(b.purchase.name)), [deadlines, filter, query, sort]);
  const grouped = useMemo(() => groupDeadlines(filtered), [filtered]);
  return <><View style={styles.title}><View><Text style={type.eyebrow}>STAY ONE STEP AHEAD</Text><Text style={type.title}>Deadline Radar</Text><Text style={[type.body, styles.subtitle]}>One calm, organized view of the dates that protect your purchases.</Text></View><Button label="Protect a purchase" icon="plus" onPress={onAdd} /></View><Card style={styles.controls}><Input accessibilityLabel="Search deadlines" value={query} onChangeText={setQuery} placeholder="Search product, merchant, or deadline type" style={styles.search} /><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filterRow}>{filters.map(([value, label]) => <Pressable accessibilityRole="button" accessibilityState={{ selected: filter === value }} key={value} onPress={() => setFilter(value)} style={[styles.filter, filter === value && styles.filterActive]}><Text style={[styles.filterText, filter === value && styles.filterTextActive]}>{label}</Text></Pressable>)}</ScrollView><View style={styles.sortRow}><Text style={type.bodySmall}>Sort by</Text>{(['urgency', 'date', 'purchase'] as Sort[]).map((value) => <Pressable accessibilityRole="button" accessibilityState={{ selected: sort === value }} key={value} onPress={() => setSort(value)} style={[styles.sort, sort === value && styles.sortActive]}><Text style={[styles.sortText, sort === value && styles.sortTextActive]}>{value[0].toUpperCase() + value.slice(1)}</Text></Pressable>)}</View></Card>{filtered.length === 0 ? <EmptyState icon="check-circle" title="You’re all caught up" message="ProofPilot will track future return, warranty, rebate, and custom deadlines here." actionLabel="Protect a purchase" onAction={onAdd} /> : <View style={styles.groups}>{groups.map((group) => <View key={group.id}><SectionHeader title={group.title} /><Text style={styles.groupDetail}>{group.detail} · {grouped[group.id].length} deadline{grouped[group.id].length === 1 ? '' : 's'}</Text>{grouped[group.id].length ? <View style={styles.grid}>{grouped[group.id].map((deadline) => <DeadlineCard key={deadline.id} deadline={deadline} onPress={() => setSelected(deadline)} />)}</View> : <Card style={styles.emptyGroup}><Text style={type.bodySmall}>Nothing scheduled in this window.</Text></Card>}</View>)}</View>}<DeadlineDetail deadline={selected} onClose={() => setSelected(null)} onOpenPurchase={(purchase) => { setSelected(null); onOpenPurchase(purchase); }} /></>;
}
function DeadlineCard({ deadline, onPress }: { deadline: NormalizedDeadline; onPress: () => void }) { return <Pressable accessibilityRole="button" accessibilityLabel={`View ${deadlineTypeLabel(deadline.type)} for ${deadline.purchase.name}`} onPress={onPress} style={({ pressed }) => [styles.cardPress, pressed && styles.pressed]}><Card style={styles.deadlineCard}><View style={styles.cardTop}><View style={[styles.icon, { backgroundColor: deadline.purchase.tint }]}><Feather name={deadline.purchase.icon} size={20} color={colors.inkSecondary} /></View><Badge label={days(deadline)} tone={tone(deadline.status)} /></View><Text style={[type.eyebrow, { marginTop: spacing.lg }]}>{deadlineTypeLabel(deadline.type)}</Text><Text numberOfLines={1} style={styles.product}>{deadline.purchase.name}</Text><Text numberOfLines={1} style={type.bodySmall}>{deadline.purchase.merchant}</Text><View style={styles.date}><Feather name="calendar" size={14} color={colors.muted} /><Text style={type.label}>{formatDate(deadline.date)}</Text></View><View style={styles.view}><Text style={styles.viewText}>View details</Text><Feather name="arrow-up-right" size={15} color={colors.brandDark} /></View></Card></Pressable>; }
function DeadlineDetail({ deadline, onClose, onOpenPurchase }: { deadline: NormalizedDeadline | null; onClose: () => void; onOpenPurchase: (purchase: Purchase) => void }) { if (!deadline) return null; return <Modal transparent visible animationType="slide" onRequestClose={onClose}><View style={styles.shade}><View style={styles.sheet}><View style={styles.handle} /><View style={styles.sheetHeader}><View><Text style={type.eyebrow}>DEADLINE DETAIL</Text><Text style={type.heading}>{deadlineTypeLabel(deadline.type)}</Text></View><IconButton icon="x" label="Close deadline details" onPress={onClose} /></View><View style={[styles.icon, { backgroundColor: deadline.purchase.tint }]}><Feather name={deadline.purchase.icon} size={22} color={colors.inkSecondary} /></View><Text style={styles.sheetProduct}>{deadline.purchase.name}</Text><Text style={type.body}>{deadline.purchase.merchant}</Text><Card style={styles.detailCard}><Detail label="Deadline type" value={deadlineTypeLabel(deadline.type)} /><Detail label="Exact date" value={formatDate(deadline.date)} /><Detail label="Status" value={days(deadline)} /><Detail label="Related documents" value={deadline.purchase.documents.length ? deadline.purchase.documents.map((document) => document.name).join(', ') : 'No documents added'} /></Card><Text style={[type.bodySmall, { marginTop: spacing.lg }]}>Reminder scheduling will be available when notifications are connected. No reminder has been sent.</Text><Button label="View purchase" icon="arrow-right" onPress={() => onOpenPurchase(deadline.purchase)} style={{ marginTop: spacing.xl }} /></View></View></Modal>; }
function Detail({ label, value }: { label: string; value: string }) { return <View style={styles.detailRow}><Text style={type.bodySmall}>{label}</Text><Text style={[type.label, styles.detailValue]}>{value}</Text></View>; }
const styles = StyleSheet.create({ title: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end', gap: spacing.lg, marginBottom: spacing.xl }, subtitle: { marginTop: spacing.sm, maxWidth: 570 }, controls: { padding: spacing.lg, marginBottom: spacing.xxl }, search: { width: '100%' }, filterRow: { gap: spacing.sm, paddingTop: spacing.md }, filter: { minHeight: 38, justifyContent: 'center', paddingHorizontal: spacing.md, borderRadius: radius.pill, backgroundColor: colors.surfaceMuted }, filterActive: { backgroundColor: colors.brand }, filterText: { ...type.label, color: colors.inkSecondary }, filterTextActive: { color: colors.ink }, sortRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, alignItems: 'center', marginTop: spacing.lg }, sort: { minHeight: 34, paddingHorizontal: spacing.md, justifyContent: 'center', borderRadius: radius.sm, borderWidth: 1, borderColor: colors.border }, sortActive: { borderColor: colors.brandDark, backgroundColor: colors.brandMuted }, sortText: { ...type.bodySmall }, sortTextActive: { color: colors.brandDark, fontWeight: '800' }, groups: { gap: spacing.xxl }, groupDetail: { ...type.bodySmall, marginTop: -spacing.sm, marginBottom: spacing.md }, emptyGroup: { padding: spacing.md, backgroundColor: colors.surfaceMuted, borderStyle: 'dashed' }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.md }, cardPress: { flexBasis: 245, flexGrow: 1, maxWidth: 390 }, deadlineCard: { padding: spacing.lg, minHeight: 230 }, cardTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: spacing.sm }, icon: { height: 43, width: 43, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center' }, product: { ...type.heading, marginTop: 3 }, date: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: spacing.md }, view: { flexDirection: 'row', alignItems: 'center', gap: 5, marginTop: 'auto', paddingTop: spacing.lg }, viewText: { ...type.label, color: colors.brandDark }, pressed: { opacity: 0.75 }, shade: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(16, 27, 39, 0.43)' }, sheet: { width: '100%', maxWidth: 520, alignSelf: 'center', borderTopLeftRadius: radius.xl, borderTopRightRadius: radius.xl, backgroundColor: colors.canvas, padding: spacing.xl, paddingBottom: 38 }, handle: { width: 38, height: 4, alignSelf: 'center', borderRadius: radius.pill, backgroundColor: colors.borderStrong, marginBottom: spacing.lg }, sheetHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: spacing.lg }, sheetProduct: { fontSize: 24, fontWeight: '800', color: colors.ink, marginTop: spacing.lg }, detailCard: { padding: spacing.lg, marginTop: spacing.xl }, detailRow: { paddingVertical: spacing.sm, borderBottomWidth: 1, borderColor: colors.border, gap: 4 }, detailValue: { color: colors.inkSecondary } });
