import React from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Feather } from '@expo/vector-icons';
import { colors, radius, spacing, type } from '../design/tokens';
import { formatDate, formatMoney, protectionLabel, type NormalizedDeadline } from '../lib/purchaseSelectors';
import type { Purchase } from '../types/purchase';
import { Badge, Card, Button } from './ui';

function toneForStatus(status: NormalizedDeadline['status']) { return status === 'overdue' || status === 'today' ? 'danger' : status === 'urgent' ? 'warning' : status === 'upcoming' ? 'success' : 'neutral'; }
function daysLabel(days: number) { return days === 0 ? 'Today' : days === 1 ? '1 day' : `${days} days`; }
export function DeadlineRow({ deadline, onPress }: { deadline: NormalizedDeadline; onPress: () => void }) { return <Pressable accessibilityRole="button" accessibilityLabel={`Review ${deadline.title} for ${deadline.purchase.name}`} onPress={onPress} style={({ pressed }) => [styles.deadline, pressed && styles.pressed]}><View style={[styles.productIcon, { backgroundColor: deadline.purchase.tint }]}><Feather name={deadline.purchase.icon} size={19} color={colors.inkSecondary} /></View><View style={styles.deadlineText}><Text style={styles.deadlineTitle}>{deadline.title}</Text><Text style={type.bodySmall}>{deadline.purchase.name} · {formatDate(deadline.date)}</Text></View><Badge tone={toneForStatus(deadline.status)} label={deadline.days < 0 ? `${Math.abs(deadline.days)} days overdue` : daysLabel(deadline.days)} /><Feather name="chevron-right" size={18} color={colors.subtle} /></Pressable>; }
export function PurchaseCard({ item, onPress }: { item: Purchase; onPress: () => void }) { const next = item.deadlines.filter((deadline) => new Date(`${deadline.date}T00:00:00Z`) >= new Date()).sort((a, b) => a.date.localeCompare(b.date))[0]; const statusTone = item.protectionStatus === 'protected' ? 'success' : item.protectionStatus === 'attention' ? 'warning' : 'neutral'; return <Pressable accessibilityRole="button" accessibilityLabel={`Open ${item.name}`} onPress={onPress} style={({ pressed }) => [styles.purchase, pressed && styles.pressed]}><Card><View style={[styles.art, { backgroundColor: item.tint }]}><View style={styles.artCircle} /><Feather name={item.icon} size={37} color={colors.inkSecondary} /><View style={styles.shield}><Feather name="shield" size={13} color={colors.success} /></View></View><View style={styles.purchaseBody}><View style={styles.purchaseHeader}><Text numberOfLines={1} style={styles.purchaseTitle}>{item.name}</Text><Feather name="more-horizontal" color={colors.subtle} size={18} /></View><Text style={type.bodySmall}>{item.merchant} · {formatDate(item.purchaseDate)}</Text><View style={styles.purchaseFooter}><Text style={styles.price}>{formatMoney(item.price)}</Text><Badge label={protectionLabel(item.protectionStatus)} tone={statusTone} /></View>{next ? <View style={styles.nextDeadline}><Feather name="clock" size={13} color={colors.muted} /><Text style={styles.nextDeadlineText}>{next.title} · {formatDate(next.date)}</Text></View> : null}</View></Card></Pressable>; }
export function StatCard({ icon, label, value, detail, tone = 'brand' }: { icon: Purchase['icon']; label: string; value: string; detail: string; tone?: 'brand' | 'warning' | 'info' | 'danger' }) { const surfaces = { brand: colors.brandMuted, warning: colors.warningSurface, info: colors.infoSurface, danger: colors.dangerSurface }; return <Card style={styles.stat}><View style={[styles.statIcon, { backgroundColor: surfaces[tone] }]}><Feather name={icon} size={18} color={colors.inkSecondary} /></View><Text style={styles.statLabel}>{label}</Text><Text style={styles.statValue}>{value}</Text><Text style={type.bodySmall}>{detail}</Text></Card>; }
export function ActionCard({ title, description, item, onPress }: { title: string; description: string; item: Purchase; onPress: () => void }) { return <Card style={styles.action}><View style={[styles.productIcon, { backgroundColor: item.tint }]}><Feather name={item.icon} size={19} color={colors.inkSecondary} /></View><View style={styles.actionBody}><Text style={styles.deadlineTitle}>{title}</Text><Text style={type.bodySmall}>{item.name} · {description}</Text></View><Button label="Review" onPress={onPress} variant="secondary" /></Card>; }
const styles = StyleSheet.create({
  pressed: { opacity: 0.75 }, deadline: { minHeight: 76, paddingVertical: spacing.md, paddingHorizontal: spacing.md, borderBottomWidth: 1, borderBottomColor: colors.border, flexDirection: 'row', alignItems: 'center', gap: spacing.md }, deadlineText: { flex: 1, minWidth: 0 }, deadlineTitle: { ...type.label, marginBottom: 3 }, productIcon: { width: 42, height: 42, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center' },
  purchase: { flexBasis: 250, flexGrow: 1, maxWidth: 390 }, art: { height: 136, alignItems: 'center', justifyContent: 'center', overflow: 'hidden', borderTopLeftRadius: radius.lg, borderTopRightRadius: radius.lg }, artCircle: { position: 'absolute', width: 106, height: 106, borderRadius: 53, backgroundColor: 'rgba(255,255,255,0.46)' }, shield: { position: 'absolute', top: spacing.md, right: spacing.md, width: 27, height: 27, borderRadius: 9, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center' }, purchaseBody: { padding: spacing.lg }, purchaseHeader: { flexDirection: 'row', gap: spacing.sm, alignItems: 'center' }, purchaseTitle: { ...type.label, flex: 1, fontSize: 14 }, purchaseFooter: { flexDirection: 'row', justifyContent: 'space-between', gap: spacing.sm, alignItems: 'center', marginTop: spacing.lg }, price: { fontSize: 17, fontWeight: '800', color: colors.ink }, nextDeadline: { flexDirection: 'row', gap: 5, alignItems: 'center', marginTop: spacing.md }, nextDeadlineText: { ...type.bodySmall, flexShrink: 1 },
  stat: { flex: 1, minWidth: 160, padding: spacing.lg }, statIcon: { height: 36, width: 36, borderRadius: 11, alignItems: 'center', justifyContent: 'center', marginBottom: spacing.md }, statLabel: { ...type.bodySmall }, statValue: { fontSize: 25, fontWeight: '800', letterSpacing: -0.8, color: colors.ink, marginVertical: 3 },
  action: { padding: spacing.md, flexDirection: 'row', alignItems: 'center', gap: spacing.md }, actionBody: { flex: 1, minWidth: 0 },
});
