import React from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, View, type TextInputProps, type ViewStyle } from 'react-native';
import { Feather } from '@expo/vector-icons';
import { colors, radius, shadows, sizing, spacing, type } from '../design/tokens';
import type { FeatherIconName } from '../types/purchase';

type ButtonProps = { label: string; onPress: () => void; icon?: FeatherIconName; variant?: 'primary' | 'secondary' | 'ghost'; accessibilityLabel?: string; style?: ViewStyle };
export function Button({ label, onPress, icon, variant = 'primary', accessibilityLabel, style }: ButtonProps) { return <Pressable accessibilityRole="button" accessibilityLabel={accessibilityLabel ?? label} onPress={onPress} style={({ pressed }) => [styles.button, styles[`button${variant}`], pressed && styles.pressed, style]}>{icon && <Feather name={icon} color={variant === 'primary' ? colors.ink : colors.brandDark} size={17} />}<Text style={[styles.buttonText, variant !== 'primary' && styles.buttonTextSecondary]}>{label}</Text></Pressable>; }
export function IconButton({ icon, label, onPress }: { icon: FeatherIconName; label: string; onPress: () => void }) { return <Pressable accessibilityRole="button" accessibilityLabel={label} onPress={onPress} style={({ pressed }) => [styles.iconButton, pressed && styles.pressed]}><Feather name={icon} size={18} color={colors.ink} /></Pressable>; }
export function Card({ children, style }: { children: React.ReactNode; style?: ViewStyle }) { return <View style={[styles.card, style]}>{children}</View>; }
export function Badge({ label, tone = 'neutral' }: { label: string; tone?: 'success' | 'warning' | 'danger' | 'neutral' }) { return <View accessibilityLabel={label} style={[styles.badge, styles[`badge${tone}`]]}><Text style={[styles.badgeText, styles[`badgeText${tone}`]]}>{label}</Text></View>; }
export function SectionHeader({ title, actionLabel, onAction }: { title: string; actionLabel?: string; onAction?: () => void }) { return <View style={styles.sectionHeader}><Text style={type.heading}>{title}</Text>{actionLabel && onAction ? <Pressable accessibilityRole="button" accessibilityLabel={actionLabel} onPress={onAction} style={({ pressed }) => [styles.textAction, pressed && styles.pressed]}><Text style={styles.textActionLabel}>{actionLabel}</Text><Feather name="arrow-up-right" color={colors.brandDark} size={15} /></Pressable> : null}</View>; }
export function Input(props: TextInputProps & { label?: string }) { const { label, ...inputProps } = props; return <View>{label ? <Text style={styles.inputLabel}>{label}</Text> : null}<TextInput {...inputProps} placeholderTextColor={colors.subtle} style={[styles.input, inputProps.style]} /></View>; }
export function EmptyState({ icon, title, message, actionLabel, onAction }: { icon: FeatherIconName; title: string; message: string; actionLabel?: string; onAction?: () => void }) { return <Card style={styles.state}><View style={styles.stateIcon}><Feather name={icon} size={22} color={colors.brandDark} /></View><Text style={type.heading}>{title}</Text><Text style={[type.body, styles.stateMessage]}>{message}</Text>{actionLabel && onAction ? <Button label={actionLabel} onPress={onAction} icon="plus" style={styles.stateButton} /> : null}</Card>; }
export function LoadingState({ label = 'Loading your protection overview…' }: { label?: string }) { return <Card style={styles.state}><ActivityIndicator color={colors.brandDark} /><Text style={[type.body, styles.stateMessage]}>{label}</Text></Card>; }
export function ErrorState({ message, onRetry }: { message: string; onRetry: () => void }) { return <Card style={styles.state}><View style={[styles.stateIcon, { backgroundColor: colors.dangerSurface }]}><Feather name="alert-circle" size={22} color={colors.danger} /></View><Text style={type.heading}>We couldn’t load this</Text><Text style={[type.body, styles.stateMessage]}>{message}</Text><Button label="Try again" onPress={onRetry} variant="secondary" icon="refresh-cw" style={styles.stateButton} /></Card>; }

const styles = StyleSheet.create({
  button: { minHeight: sizing.touch, borderRadius: radius.md, paddingHorizontal: spacing.lg, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: spacing.sm },
  buttonprimary: { backgroundColor: colors.brand }, buttonsecondary: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.borderStrong }, buttonghost: { backgroundColor: 'transparent' }, buttonText: { ...type.label, color: colors.ink }, buttonTextSecondary: { color: colors.brandDark }, pressed: { opacity: 0.76 },
  iconButton: { height: sizing.iconButton, width: sizing.iconButton, borderRadius: radius.md, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface },
  card: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radius.lg, ...shadows.card },
  badge: { alignSelf: 'flex-start', borderRadius: radius.pill, paddingHorizontal: spacing.sm, paddingVertical: 4 }, badgeText: { fontSize: 11, lineHeight: 14, fontWeight: '800' },
  badgesuccess: { backgroundColor: colors.successSurface }, badgeTextsuccess: { color: colors.success }, badgewarning: { backgroundColor: colors.warningSurface }, badgeTextwarning: { color: colors.warning }, badgedanger: { backgroundColor: colors.dangerSurface }, badgeTextdanger: { color: colors.danger }, badgeneutral: { backgroundColor: colors.surfaceMuted }, badgeTextneutral: { color: colors.inkSecondary },
  sectionHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: spacing.md, gap: spacing.md }, textAction: { minHeight: sizing.touch, flexDirection: 'row', alignItems: 'center', gap: 5, paddingHorizontal: spacing.sm }, textActionLabel: { ...type.label, color: colors.brandDark },
  inputLabel: { ...type.eyebrow, marginBottom: 6 }, input: { height: sizing.touch, borderRadius: radius.md, borderWidth: 1, borderColor: colors.borderStrong, backgroundColor: colors.surface, paddingHorizontal: spacing.md, color: colors.ink, fontSize: 14 },
  state: { alignItems: 'center', padding: spacing.xxl, textAlign: 'center' }, stateIcon: { width: 48, height: 48, borderRadius: radius.lg, backgroundColor: colors.brandMuted, alignItems: 'center', justifyContent: 'center', marginBottom: spacing.md }, stateMessage: { textAlign: 'center', maxWidth: 360, marginTop: spacing.sm }, stateButton: { marginTop: spacing.lg },
});
